### ISSUE TITLE
kubectl krew failed to install plugin "virt": checksum does not match

### ISSUE THREAD

**Issue by fsando** [kubevirt/kubectl-virt-plugin#12]
On ubuntu 18.04

Trying to install plugin virt results in a failure

What I did:
kubectl krew install virt

What I expected:
That plugin virt would be installed

What happened (the full command and response):

$ kubectl krew install virt
Updated the local copy of plugin index.
Installing plugin: virt
W1213 22:39:49.275411   28501 install.go:128] failed to install plugin "virt": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 45dee1e962164ea69c0a8c8d300d258007380f1e2b9d292e414719eacb69837e, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
F1213 22:39:49.275534   28501 root.go:58] failed to install some plugins: [virt]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 45dee1e962164ea69c0a8c8d300d258007380f1e2b9d292e414719eacb69837e, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

**Comment by fsando** [comment]
Update:
Apparently the download url has changed:
Manually changing the url in the virt.yaml from

https://github.com/dhiller/...
to
https://github.com/kubevirt/...

and running the install with --no-update-index works around the bug:
kubectl krew install with --no-update-index:

**Comment by dhiller** [comment]
@fsando thanks for pointing this out. I've created an updated package with this PR: https://github.com/kubernetes-sigs/krew-index/pull/393

**Comment by dhiller** [comment]
kubernetes-sigs/krew-index#393 was merged. It should work now. Can you check please? Thanks!

**Comment by dhiller** [comment]
I've tested the install locally myself. It works.

/close
