### ISSUE TITLE
virt console can't  login into the vm

### ISSUE THREAD

**Issue by Icedroid** [kubevirt/kubectl-virt-plugin#32]
❯ kubectl virt console vm-test      
Can't connect to websocket (404): websocket: bad handshake

**Comment by dhiller** [comment]
Hey @Icedroid, have you tried using the sole virtctl binary from [the KubeVirt releases](https://github.com/kubevirt/kubevirt/releases)? Did you achieve the same result? Also, what exactly did you do before this?

**Comment by dhiller** [comment]
Another question: what kubevirt version have you deployed?
