### ISSUE TITLE
Plugin not supported over Mac M1 Chip 

### ISSUE THREAD

**Issue by Abhishek1121-tech** [kubevirt/kubectl-virt-plugin#34]
Hi Team,

Need attention here, the plugin is not supported as per ARM-based systems. 
Please share your thought on this.

`  kubectl krew install virt
+-zsh:23> kubectl krew install virt
Updated the local copy of plugin index.
Installing plugin: virt
W0722 13:21:30.600730    6279 install.go:164] failed to install plugin "virt": plugin "virt" does not offer installation for this platform
failed to install some plugins: [virt]: plugin "virt" does not offer installation for this platform`

**Comment by Daemoen** [comment]
Any update/progress/plan for this ?

**Comment by stu-gott** [comment]
@dhiller how difficult would it be for us to build an ARM architecture copy of the plugin?

@Abhishek1121-tech @Daemoen please understand if we're able to provide binaries, they'll be best-effort. We don't have ARM infrastructure with which to automate testing.

**Comment by dhiller** [comment]
IIRC we don't build the binary for ARM currently.

We would need to
* create a new arm binary [in the build](https://github.com/kubevirt/kubevirt/blob/b5b88c9a066401aa0a328520203fe1c3129d4d83/cmd/virtctl/BUILD.bazel), then
* add the [binary to the published binaries](https://github.com/kubevirt/kubevirt/blob/5497e6d4829673a6c3cebcbdafb6bf64c05f7afa/automation/release.sh#L58), and then
* eventually fix [kubectl-virt-plugin package creation](https://github.com/kubevirt/kubectl-virt-plugin/blob/927a9a99e6200d61a7a1a010791cd82a3df07438/scripts/functions#L105) for the new binary

**Comment by dhiller** [comment]
@rmohr I think we are building the arm binaries for the kubevirt components as cross compile, so this should be possible, right?

**Comment by rmohr** [comment]
/remove-lifecycle stale
/lifecycle frozen



> @rmohr I think we are building the arm binaries for the kubevirt components as cross compile, so this should be possible, right?

Yes, we just need to add it to the release artifact. Everything is set up to build it natively for arm and add it to the release uploads.

**Comment by rmohr** [comment]
> @dhiller how difficult would it be for us to build an ARM architecture copy of the plugin?
> 
> @Abhishek1121-tech @Daemoen please understand if we're able to provide binaries, they'll be best-effort. We don't have ARM infrastructure with which to automate testing.

And this too, but we are on a good path :)

**Comment by cwilson613** [comment]
The M1 chip has been around for a while, and support has largely stabilized.  This plugin remains one of the few toolchain elements that doesn’t yet.

**Comment by rmohr** [comment]
We now have arm binaries released: https://github.com/kubevirt/kubevirt/releases/tag/v1.0.0. @dhiller probably possible now to add them to the plugin?

**Comment by tdensmore** [comment]
Do you need volunteers for this? I would like to push this issue forward.

**Comment by crabique** [comment]
Will arm64 binaries be available with next release only?
