### ISSUE TITLE
Update the krew index for the latest release

### ISSUE THREAD

**Issue by vicaya** [kubevirt/kubectl-virt-plugin#36]
krew is still pointing to 1.0.1, so `kubectl virt` is complaining but version mismatch.

It'd be great if the update is automated: https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/

**Comment by dhiller** [comment]
@vicaya thanks for the heads up. Seems the automation has hit a rate limit:

```
time="2023-11-07T00:02:36Z" level=fatal msg="GET https://api.github.com/repos/kubevirt/kubectl-virt-plugin/releases/tags/v1.1.0: 403 API rate limit exceeded for 52.159.142.194. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 10m04s]"
```
[source](https://github.com/kubevirt/kubectl-virt-plugin/actions/runs/6778032764/job/18422776826)

I'll retrigger the action and see how it goes.

**Comment by dhiller** [comment]
After retriggering the action the [PR was created against krew index](https://github.com/kubernetes-sigs/krew-index/pull/3494/), in general the automation will merge it within a short time range

**Comment by dhiller** [comment]
Hmmm, the [PR list for krew-index](https://github.com/kubernetes-sigs/krew-index/pulls) shows a lot of PRs created by krew release bot, not sure what's up there...

**Comment by dhiller** [comment]
But the automation seems to work: https://github.com/kubernetes-sigs/krew-index/pull/3492

/close

@vicaya please reopen if it still doesn't work in two days.
